//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PuntoDeVenta.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARTICULOS
    {
        public int ID { get; set; }
        public string CODIGO { get; set; }
        public string DESCRIPCION { get; set; }
        public int EXISTENCIA { get; set; }
        public decimal PRECIO { get; set; }
    }
}
