//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PuntoDeVenta.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARTICULOS_VENTA
    {
        public int ID { get; set; }
        public int ID_ARTICULO { get; set; }
        public int ID_VENTA { get; set; }
        public decimal MONTO_ARTICULO { get; set; }
        public int ID_VENTA1 { get; set; }
    }
}
