//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PuntoDeVenta.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTES
    {
        public int ID { get; set; }
        public string NOMBRE { get; set; }
        public string A_PATERNO { get; set; }
        public string A_MATERNO { get; set; }
        public int EDAD { get; set; }
        public string NUM_TELEFONO { get; set; }
    }
}
