//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PuntoDeVenta.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VENTAS
    {
        public int ID { get; set; }
        public int ID_CLIENTE { get; set; }
        public System.DateTime FECHA { get; set; }
        public string TIPO_PAGO { get; set; }
        public decimal MONTO { get; set; }
    
        public virtual VENTAS VENTAS1 { get; set; }
        public virtual VENTAS VENTAS2 { get; set; }
    }
}
